version: '3.1'
services:
    webserver:
        image: puckel/docker-airflow:1.10.7
        restart: always
        environment:
           # Loads DAG examples
            - LOAD_EX=y
        networks:
          airflow-sandbox-network:
            ipv4_address: 112.18.0.22
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8081:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3 

networks:
  airflow-sandbox-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 112.18.0.0/16
